name: Self building inside a container via workflow

on:
  workflow_dispatch:
  push:
    branches: [ "feature/*" ]
    paths:
    - 'frontend/**'
    - 'catalog/**'
    - 'ordering/**'

jobs:
  container_build:
    runs-on: ubuntu-latest
    container: 
      image: mcr.microsoft.com/dotnet/sdk:6.0
      volumes:
        - ${{github.workspace}}:/src # a volume to store contents to
    steps:
    - name: checkout
      uses: actions/checkout@4.2.2

    - name: fixing things
      run: |
        apt update && apt upgrade -y
        apt-get install libglib2.0-0 libnss3 libnspr4 libatk1.0-0 libatk-bridge2.0-0 libcups2 libdrm2 libdbus-1-3 libxcb1 libxkbcommon0 libatspi2.0-0 libx11-6 libxcomposite1 libxdamage1 libxext6 libxfixes3 libxrandr2 libgbm1 libpango-1.0-0 libcairo2 libasound2
    - name: dotnet build
      run: |
        dotnet restore ; dotnet build --no-restore
    - name: add markdown
      run: |
        dotnet add unittests/unittests.csproj package LiquidTestReports.Markdown
    - name: Test
      run: dotnet test --logger "liquid.md;logFilename=testResults.md"
    - name: Output the results to summary page of workflow
      run: cat $(find . -type f -name testResults.md) >> $GITHUB_STEP_SUMMARY
    - name: Build with dotnet
      run: dotnet build frontend/frontend.csproj --configuration Release

    
