name: "Self writing the workflow for compiling and test fast feedback"
permissions:
  contents: read
  actions: write

on:
  push:
    branches: 
    - 'frontend/**'
    - 'catalog/**'
    - 'ordering/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Installing dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Restoring dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore

    - name: add markdown report on the workflow summary page
      run: dotnet add unittests/unittests.csproj package LiquidTestReports.Markdown

    - name: Test
      run: dotnet test --logger "liquid.md;logFilename=testResults.md"
    - name: Output the results to summary page of workflow
      run: cat $(find . -type f -name testResults.md) >> $GITHUB_STEP_SUMMARY
